Total current
jrester/tesla_powerwall pull request #25
Opened 2021-04-25 17:42 UTC by quielb

Adds access to the instant_total_curent meter via get function

2021-04-25 17:44 UTC, quielb commented
Resolves #24

2021-04-26 07:08 UTC, jrester requested changes
Thanks for submitting! Just one change I would suggest ;)

2021-04-26 07:08 UTC, jrester commented on tesla_powerwall/responses.py
> +        return round(self.assert_attribute("instant_total_current"), precision)
Could you replace the `assert_attribute` with the direct access to the property to make it conform with the other methods?

2021-04-26 15:35 UTC, jrester approved these changes

2021-04-26 15:37 UTC, merged

2021-04-26 15:38 UTC, jrester commented
Great, Thanks!